name: what
recipe: drupal8
config:
  # Optionally specify a webroot if it is a subdirectory of the appRoot
  webroot: web

  via: nginx

  database: mariadb:10.1

proxy:
  appserver:
    - pl.fpm.lndo.site:3000
    - pl.fpm.lndo.site:3001

services:
  appserver:
    type: php:custom
    overrides:
      services:
        # Use custom php imag eto include node in our appserver to run patternlab
        image: fosterinteractive/docker-mainspring-php-pl:1.0-fpm
        # Make the default browsersync ports available.
        # Bug: Currently the ports are not being passed to nginx server.
        # ports:
        #   - 3000:3000
        #   - 3001:3001
    run_as_root:
      - "cd $LANDO_WEBROOT/themes/mainspring && npm run init"

  node:
    type: node:9
    globals:
      gulp-cli: "latest"
    overrides:
      services:
        ports:
          - 3000:3000
          - 3001:3001

tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  composer:
    service: appserver
